baseURL: https://masputrawae.github.io/gas-poll
languageCode: id
title: Contoh Situs
timeZone: Asia/Jakarta
enableEmoji: true

#===================
# PAGINATION
#===================
pagination:
  disableAliases: false
  pagerSize: 20
  path: page

#===================
# TAXONOMIES
#===================
taxonomies:
  tag: tags
  category: categories

#===================
# CUSTOM OUTPUT
#===================
mediaType: "application/json"
outputFormats:
  search:
    mediaType: "application/json"
    baseName: "search"
    isPlainText: true
    notAlternative: true

  manifest:
    mediaType: "application/json"
    baseName: "manifest"
    isPlainText: true
    notAlternative: true

outputs:
  home:
    - html
    - rss
    - sitemap
    - search
    - manifest
    
module:
  hugoVersion:
    extended: true
    min: 0.149.0
    
  mounts:
    - source: node_modules/bootstrap-icons/icons
      target: assets/icons

    - source: assets
      target: assets

    - source: assets/images
      target: static

    - source: images
      target: static

    - source: static
      target: static
