main:
  - name: Main Page
    pageRef: /000_Main_Page
    weight: 10

  - name: About
    pageRef: /001_About_Me
    weight: 20

  - name: Recent Change
    pageRef: /recent_change
    weight: 30

  - name: Random Page
    pageRef: /random_page/
    weight: 40

  - name: Tags
    pageRef: /tags
    weight: 50

  - name: Categories
    pageRef: /categories
    weight: 60
