main:
  - name: Beranda
    pageRef: /
    weight: 10
    params: { icon: house }
  - name: Tag
    pageRef: /tags
    weight: 20
    params: { icon: tags }
  - name: Taman Digital
    pageRef: /digital-garden
    weight: 30
    params: { icon: tree }
  - name: Referensi
    pageRef: /references
    weight: 40
    params: { icon: folder-symlink }
  - name: Tentang
    pageRef: /about
    weight: 50
    params: { icon: person-circle }
