main:
  - name: Main Page
    pageRef: /main_page/
    weight: 10
  - name: About
    pageRef: /specials/about
    weight: 20
  - name: Random Page
    pageRef: /random_page
    weight: 30
  - name: Tags
    pageRef: /tags
    weight: 40
  - name: Categories
    pageRef: /categories/
    weight: 50
