author: Putra Jaya
tagline: Hanya Seorang Manusia Biasa
description: Catatan perjalanan belajarku, penuh spontanitas, ide liar, dan potongan referensi untuk masa depan.
logo: logo.png

siteType: "CreativeWork"
publisherType: "Person"
publisherName: "Putra Jaya"

images: # ===== IMAGES =====
  - default-image.webp
  - logo.png

social: # ===== SOCIAL =====
    facebook_admin: "61566134978045"
    facebook_app_id: "1112672776879424"
    twitter: Masputrawae

footer: # ===== FOOTER =====
  custom: |
    <p>
      <span>Made with ❤️ using</span>
      <a href="https://gohugo.io/" class="link link--external">Hugo</a>.
    </p>
  license: | 
    <p>
      <span>Content licensed under</span>
      <a href="https://creativecommons.org/licenses/by-nc/4.0/" class="link link--external">CC BY-NC 4.0</a>
    </p>

favicons: # ===== FAVICONS =====
  - rel: icon
    type: image/x-icon
    href: favicon.ico

  - rel: apple-touch-icon
    type: image/png
    size: 180x180
    href: apple-touch-icon.png

  - rel: icon
    type: image/png
    size: 32x32
    href: favicon-32x32.png

  - rel: icon
    type: image/png
    size: 16x16
    href: favicon-16x16.png

  - rel: icon
    type: image/png
    size: 192x192
    href: android-chrome-192x192.png

  - rel: icon
    type: image/png
    size: 512x512
    href: android-chrome-512x512.png

fonts:
  - name: Inter
    path: inter-v20-latin-regular.woff2
    weight: 400
    type: woff2
  
  - name: Inter
    path: inter-v20-latin-500.woff2
    weight: 500
    type: woff2
  
  - name: Inter
    path: inter-v20-latin-600.woff2
    weight: 600
    type: woff2
  
  - name: Inter
    path: inter-v20-latin-700.woff2
    weight: 700
    type: woff2
  
  - name: Inter
    path: inter-v20-latin-800.woff2
    weight: 800
    type: woff2
  
  - name: Roboto Mono
    path: roboto-mono-v31-latin-regular.woff2
    weight: 400
    type: woff2

  - name: Roboto Mono
    path: roboto-mono-v31-latin-700.woff2
    weight: 700
    type: woff2