#============== BASE ==============#
baseURL           = 'https://masputrawae.github.io/'
languageCode      = "id"
title             = "Putra Jaya"
enableEmoji       = true
buildFuture       = true

[permalinks]
  tutorial = '/:title/'
  notes = '/:year/:month/:day/:title/'
  projects = '/:title/'
  vocab = '/:title/'

#============== PARAMS ==============#
[params]
  author        = "Putra Jaya"
  tagline       = "Manusia Biasa"
  description   = "Catatan-catatan pribadi yang mungkin hanya berguna untuk saya sendiri, atau mungkin alien di masa depan, siapa tahu?"
  logo          = "logo/logo.png"
  thumbnail     = "images/for-blog.jpg"

#============== GOOGLE ANALYTICS ==============#
[services]
  [services.googleAnalytics]
    id = 'G-W9TMTZZYG5'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false

#============== MENU MAIN ==============#
  [[menus.main]]
  name           = 'Home'
  pageRef        = '/'
  params         = {icon = "icon--house-door"}
  weight         = 10

  [[menus.main]]
  name           = 'About'
  pageRef        = '/about'
  params         = {icon = "icon--person"}
  weight         = 20

  [[menus.main]]
  name           = 'Projects'
  pageRef        = '/projects'
  params         = {icon = "icon--kanban"}
  weight         = 30


  [[menus.main]]
  name           = 'Notes'
  pageRef        = '/notes'
  params         = {icon = "icon--journal-text"}
  weight         = 40

  [[menus.main]]
  name           = 'Tutorial'
  pageRef        = '/series'
  params         = {icon = "icon--tools"}
  weight         = 50

  [[menus.main]]
  name           = 'Search'
  pageRef        = '/search'
  params         = {icon = "icon--search"}
  weight         = 60

#   [[menus.main]]
#   name           = 'Gallery'
#   pageRef        = '/gallery'
#   params         = {icon = "icon--images"}
#   weight         = 40

#============== MENU SOCIAL ==============#
  [[menus.social]]
  name        = "Instagram"
  url         = "https://www.instagram.com/masputrawae/"
  params      = {icon = "icon--instagram"}
  weight      = 10

  [[menus.social]]
  name        = "Github"
  url         = "https://github.com/masputrawae"
  params      = {icon = "icon--github"}
  weight      = 20

  [[menus.social]]
  name        = "Discord"
  url         = "https://discord.gg/nM4EP8DJFZ"
  params      = {icon = "icon--discord"}
  weight      = 30

#============== PAGINATION ==============#
[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

#============== MODULE ==============#
[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = "templates/*"
  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = ".obsidian/*"
  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = ".trash/*"
  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = "private/*"

#============== MARKUP ==============#
[markup]
  [markup.highlight]
    codeFences          = true
    guessSyntax         = true
    style               = "github-dark"
    noClasses           = true
    lineNumbersInTable  = true
    lineNos             = false
    anchorLineNos       = false
    lineAnchors         = ''
    lineNoStart         = 1
    tabWidth            = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe    = true

    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      
      [markup.goldmark.parser.attribute]
        block = true
        title = true

#============== OUTPUT ==============#
[outputFormats]

  [outputFormats.search-data]
    mediaType       = "application/json"
    baseName        = "search-data"
    isPlainText     = true
    notAlternative  = true
    
  [outputFormats.manifest]
    mediaType       = "application/json"
    baseName        = "manifest"
    isPlainText     = true
    notAlternative  = true

[outputs]
  home = ['html', "search-data", "manifest"]
  page = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']
