name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5

      - name: Clone document repository
        uses: actions/checkout@v5
        with:
          repository: masputrawae/Documents
          token: ${{ secrets.DOCUMENTS }}
          path: docs

      - name: Create vault
        run: mkdir -p vault

      - name: Copy Content
        run: cp -r ./docs/published ./vault/content

      - name: Copy Assets
        run: cp -r ./docs/attachments/shared ./vault/assets

      - name: Install, build, and upload your site
        uses: withastro/action@v5
        with:
          node-version: 24 # The specific version of Node that should be used to build your site. Defaults to 22. (optional)
          # package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
          build-cmd: pnpm run build # The command to run to build your site. Runs the package build script/task by default. (optional)

      - name: Cleanup Vault Git
        run: rm -rf ./docs

      - name: Check All
        run: ls -a

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
